timezone: America/Toronto
dailyDigestSchedule: "0 9 * * *"

sources:
  - id: guelph
    name: Guelph Humane Society
    enabled: true
    adapter: adopets
    url: "https://iframe.adopets.com/guelph-humane-society?shelter_uuid=ef63c7cd-7e2d-4db2-b356-534fef0e1bb5&g=15&p=15&t=true&nb=false&al_show=true"
    publicUrl: "https://guelphhumane.ca/adopt/available-animals/"
    schedule: "17 * * * *"
    allowEmpty: false
    notifyRelisted: false
    filters: {}

  - id: cambridge
    name: Cambridge & District Humane Society
    enabled: true
    adapter: petango
    url: "https://cambridgehumanesociety.org/adoption/adopt-a-dog/"
    schedule: "32 * * * *"
    allowEmpty: false
    notifyRelisted: false
    filters: {}

  - id: kwsp
    name: Humane Society of Kitchener Waterloo & Stratford Perth
    enabled: true
    adapter: petango
    url: "https://kwsphumane.ca/adopt/dogs"
    schedule: "47 * * * *"
    allowEmpty: false
    notifyRelisted: false
    filters: {}

  - id: oxford
    name: Oxford County Animal Rescue
    enabled: true
    adapter: adoptapet
    url: "https://www.oxfordcountyanimalrescue.com/dogs-for-adoption.html"
    schedule: "5 * * * *"
    allowEmpty: false
    notifyRelisted: false
    filters: {}

  - id: safepaws
    name: Safe Paws Animal Rescue of Ontario
    enabled: true
    adapter: safepaws
    url: "https://www.safepawsanimalrescue.com/animalsforadoption"
    schedule: "57 * * * *"
    allowEmpty: false
    notifyRelisted: false
    filters: {}

  - id: standard-poodles
    name: Standard Poodles in Need
    enabled: true
    adapter: html
    url: "https://standardpoodlesinneed.com/available-dogs/"
    schedule: "12 * * * *"
    allowEmpty: false
    notifyRelisted: false
    filters: {}
    selectors:
      item: ".Bzl-dog-post.type-dog"
      name: ".Bzl-dog-heading > a"
      link: ".Bzl-dog-heading > a"
      image: ".Bzl-dog-img img"
      status: ".Bzl-pending"

  - id: golden-rescue
    name: Golden Rescue
    enabled: true
    adapter: goldenrescue
    url: "https://goldenrescue.ca/our-goldens/adopt-3/?status=available#adoptions"
    schedule: "22 * * * *"
    allowEmpty: false
    notifyRelisted: false
    filters: {}

  - id: ontario-spca-orangeville
    name: Ontario SPCA - Orangeville
    enabled: true
    adapter: ontariospca
    url: "https://ontariospca.ca/adopt/?location=orangeville&order=default&pageNumber=1"
    schedule: "27 * * * *"
    allowEmpty: true
    notifyRelisted: false
    filters: {}

  - id: welcome-dog-korea-toronto-large
    name: Welcome Dog Korea - Toronto Large Dogs
    enabled: true
    adapter: welcomedogkorea
    url: "https://www.welcomedogkorea.org/find-a-dog?page=1&location=Toronto&size=large&status=&search="
    schedule: "37 * * * *"
    allowEmpty: true
    notifyRelisted: false
    filters: {}
